# Generated by Django 3.2.16 on 2023-02-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0002_alter_trip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
