# Generated by Django 3.2.16 on 2023-02-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0004_auto_20230215_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
