# Generated by Django 3.2.16 on 2023-02-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0005_alter_trip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='matches',
            field=models.TextField(blank=True, null=True),
        ),
    ]
