# Generated by Django 3.2.16 on 2023-02-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0008_auto_20230228_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='_carpooling_trip_requests_+', to='carpooling.Trip'),
        ),
    ]
