# Generated by Django 3.2.16 on 2023-03-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0018_auto_20230314_1620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
